request_generator:
  first_no_reuse: 200
  content_generator:
    new_string_generator:
      reuse_ratio_generator:
        left: 1.0
        provider: uniform
        right: 1.0
    old_string_generator:
      request_selection_generator:
        provider: fixed_distance
        distance: 200
  local_files_only: false
  provider: synthetic
  shape_generator:
    num_requests: 600
    provider: synthetic
    request_interval_generator:
      provider: poisson
      qps: 5.0
    request_length_generator:
      max_tokens: 15000
      min_tokens: 15000
      prefill_to_decode_ratio: 1500
      provider: uniform
    seed: 39
  tokenizer_name: bert-base-uncased
  tokenizer_type: transformers
seed: 39

# prefix reuse ratio generally: 2/3
# size 3000000
# copy pattern: cyclic