request_generator:
  content_generator:
    new_string_generator:
      no_reuse_probability: 0.2
      reuse_ratio_generator:
        left: 0.83
        provider: uniform
        right: 0.83
    old_string_generator:
      request_selection_generator:
        provider: latest
  local_files_only: true
  provider: synthetic
  shape_generator:
    num_requests: 600
    provider: synthetic
    request_interval_generator:
      provider: poisson
      qps: 5.0
    request_length_generator:
      max_tokens: 15000
      min_tokens: 15000
      prefill_to_decode_ratio: 1500
      provider: uniform
    seed: 42
  tokenizer_name: bert-base-uncased
  tokenizer_type: transformers
seed: 42

# prefix reuse ratio generally: 0.8 * 0.83 = 0.664(0.6612334444444444)
# size 3048899(error rate 1.6%)
# copy pattern: latest